### PR TITLE
Draft: version bumps in dependencies

### PR DESCRIPTION
**Pull request by badrbouslikhin**
Hello,

I wanted to bring to your attention some compilation issues that I encountered while trying to start a new Bluetooth Mesh project based on the [drogue-device](https://github.com/drogue-iot/drogue-device/tree/main/examples/nrf52/microbit/bt-mesh) repository. Specifically, I ran into issues related to dependencies updates, including `embassy-sync`, `embassy-nrf`, `nrf-softdevice`, and `embedded-storage-async`. Additionally, some of these issues were also related to recent Rust nightlies, specifically TAIT for async traits.

I have created a draft pull request to address these issues, and I would be happy to make any necessary changes that you may suggest. 

Note: one of the commits (105a07685923723b4e837fce8ac9edcd937d6764) contains numerous modifications related to formatting.

Thank you for your time working on this project!

### CODE REVIEW

**Review by lulf — APPROVED** [review]
Thanks for the updates, looks good to me.

**Comment by badrbouslikhin** [comment]
Just wanted to let you know that I've made some new commits that should fix the compilation issues in the examples. Could you take a quick look at [d275be6](https://github.com/drogue-iot/btmesh/pull/20/commits/d275be6b90e209fba9648af677c5a889ee4b10a1) and let me know what you think?

Also, I've been having some trouble with the `cargo test` job in CI. I've been trying to figure it out, but it seems related to `embassy-time` and its std features. Any ideas on how to fix this?

Thanks for your help!

**Comment by lulf** [comment]
That commit looks good, saving that clone is great.

I'll look into the CI failures, I think some flag on critical-section is needed maybe.

**Comment by badrbouslikhin** [comment]
Commit [a4ca5a0](https://github.com/drogue-iot/btmesh/pull/20/commits/a4ca5a0c2b85a2db630342e341d9d98f337e77d9) enables the `rt` feature gate in the Embassy nRF HAL, which was introduced in commit [8c93805](https://github.com/embassy-rs/embassy/commit/8c93805ab5a13c784e072c8e6e59b354ee902d99).

Enabling this feature gate was necessary to make the examples functional, as the binding was not working without it.

**Comment by lulf** [comment]
@badrbouslikhin Can you apply this change:

diff --git a/btmesh-driver/Cargo.toml b/btmesh-driver/Cargo.toml
index 40b8899..abc3e04 100644
--- a/btmesh-driver/Cargo.toml
+++ b/btmesh-driver/Cargo.toml
@@ -17,6 +17,7 @@ embassy-sync = { version = "0.2.0", default-features = false, features = [
   "nightly",
 ] }
 embassy-futures = { version = "0.1.0", default-features = false }
+critical-section = { version = "1.1.1", default-features = false, optional = true }
 heapless = "0.7"
 hash32 = "0.2.1"
 hash32-derive = "0.1.1"
@@ -40,7 +41,7 @@ rand_core = { version = "0.6.2", default-features = false, features = [
 
 [features]
 default = ["flash", "memory", "relay", "std"]
-std = ["embassy-time/std"]
+std = ["embassy-time/std", "critical-section/std"]
 flash = [
   "embedded-storage",
   "embedded-storage-async",

**Comment by badrbouslikhin** [comment]
Thanks! It works locally for me too. Let's see if the CI is happy.

**Pull request merged**
